export const itemIds = [
  { Name: "Crystalline Spear", ID: "11610" },
  { Name: "Block of Permafrost", ID: "20665" },
  { Name: "Dragon Bone Bracelet", ID: "11606" },
  { Name: "Kavruul`s Mystic Pouch", ID: "17701" },
  { Name: "McVaxius` Horn of War", ID: "11607" },
  { Name: "McVaxius` Horn of War", ID: "11607" },
  { Name: "Runed Bolster Belt", ID: "11601" },
  { Name: "Scimitar of the Mistwalker", ID: "11604" },
  { Name: "Spell: Ice Comet", ID: "15732" },
  { Name: "Staff of Forbidden Rites", ID: "11608" },
  { Name: "Tobrin's Mystical Eyepatch", ID: "11052" },
  { Name: "Torn, Frost covered book", ID: "19070" },
  { Name: "Warhammer of Divine Grace", ID: "11611" },
  { Name: "White Dragon Scales", ID: "11602" },
  { Name: "White Dragon Tooth", ID: "11605" },
  { Name: "White Wolf-hide Girdle", ID: "2900" },
  { Name: "Bladestopper", ID: "11632" },
  { Name: "Blight, Hammer of the Scourge", ID: "11628" },
  { Name: "Cloak of Flames", ID: "11621" },
  { Name: "Gauntlets of Fiery Might", ID: "11624" },
  { Name: "Gold Plated Koshigatana", ID: "11630" },
  { Name: "Hierophant`s Crook", ID: "11629" },
  { Name: "Orb of Tishan", ID: "11625" },
  { Name: "Prayers of Life", ID: "11631" },
  { Name: "Red Dragon Scales", ID: "11622" },
  { Name: "Red Dragon Tooth", ID: "11627" },
  { Name: "Selo`s Drums of the March", ID: "11626" },
  { Name: "Torn, burnt book", ID: "19071" },
  { Name: "Treasure Hunter`s Satchel", ID: "17702" },
  { Name: "Polished Mithril Torque", ID: "4501" },
  { Name: "Crown of King Tranix", ID: "4504" },
  { Name: "Polished Mithril Mask", ID: "4505" },
  { Name: "Rokyls Channelling Crystal", ID: "10219" },
  { Name: "Mithril Vambraces", ID: "4411" },
  { Name: "Mithril Greaves", ID: "4412" },
  { Name: "Razing Sword of Skarlon", ID: "5412" },
  { Name: "Blue Crystal Staff", ID: "14337" },
  { Name: "Kedge Backbone", ID: "20524" },
  { Name: "Robe of the Kedge", ID: "1253" },
  { Name: "Rod of Malisement", ID: "10374" },
  { Name: "Staff of Elemental Mastery: Water", ID: "11569" },
  { Name: "Trident of the Seven Seas", ID: "7510" },
  { Name: "Wand of Mana Tapping", ID: "10375" },
  { Name: "Fusible Coral Ore", ID: "2447" },
  { Name: "Rune Etched Helm", ID: "4871" },
  { Name: "Rune Etched Chestplate", ID: "4872" },
  { Name: "Rune Etched Vambraces", ID: "4873" },
  { Name: "Rune Etched Bracer", ID: "4874" },
  { Name: "Rune Etched Gauntlets", ID: "4875" },
  { Name: "Rune Etched Greaves", ID: "4876" },
  { Name: "Rune Etched Boots", ID: "4877" },
  { Name: "Scaled Hierophant Boots", ID: "5182" },
  { Name: "Scaled Hierophant Gauntlets", ID: "5183" },
  { Name: "Scaled Hierophant Vambraces", ID: "5184" },
  { Name: "Scaled Hierophant Greaves", ID: "5185" },
  { Name: "Scaled Hierophant Bracers", ID: "5186" },
  { Name: "Scaled Hierophant Breastplate", ID: "5187" },
  { Name: "Scaled Hierophant Helm", ID: "5188" },
  { Name: "Scaled Hierophant Cloak", ID: "5189" },
  { Name: "Runewood Shield", ID: "9406" },
  { Name: "Spitestone Shield", ID: "9407" },
  { Name: "Imbrued Platemail Helm", ID: "4861" },
  { Name: "Imbrued Platemail Breastplate", ID: "4862" },
  { Name: "Imbrued Platemail Vambraces", ID: "4863" },
  { Name: "Imbrued Platemail Bracer", ID: "4864" },
  { Name: "Imbrued Platemail Gauntlets", ID: "4865" },
  { Name: "Imbrued Platemail Greaves", ID: "4866" },
  { Name: "Imbrued Platemail Boots", ID: "4867" },
  { Name: "Martune Rapier", ID: "7509" },
  { Name: "Star Ruby", ID: "10032" },
  { Name: "Apothic Crown", ID: "1239" },
  { Name: "Apothic Robe", ID: "1240" },
  { Name: "Apothic Sleeves", ID: "1241" },
  { Name: "Apothic Warband", ID: "1242" },
  { Name: "Apothic Gloves", ID: "1243" },
  { Name: "Apothic Kilt", ID: "1244" },
  { Name: "Apothic Boots", ID: "1245" },
  { Name: "Insidious Halo", ID: "1246" },
  { Name: "Insidious Robe", ID: "1247" },
  { Name: "Insidious Sleeves", ID: "1248" },
  { Name: "Insidious Manacle", ID: "1249" },
  { Name: "Insidious Gloves", ID: "1250" },
  { Name: "Insidious Pantaloons", ID: "1251" },
  { Name: "Insidious Slippers", ID: "1252" },
  { Name: "Wand of Swiftness", ID: "12506" },
  { Name: "Wand of Swords", ID: "12502" },
  { Name: "Essence of a Vampire", ID: "10624" },
  { Name: "Staff of Elemental Mastery: Fire", ID: "11566" },
  { Name: "Woven Shadow Helm", ID: "4901" },
  { Name: "Woven Shadow Chestplate", ID: "4902" },
  { Name: "Woven Shadow Bracer", ID: "4904" },
  { Name: "Woven Shadow Gauntlets", ID: "4905" },
  { Name: "Star Ruby Earring", ID: "10048" },
  { Name: "Prismatic Shield", ID: "9405" },
  { Name: "Ethereal Mist Chestplate", ID: "4882" },
  { Name: "Ethereal Mist Boots", ID: "4887" },
  { Name: "Ethereal Mist Bracers", ID: "4884" },
  { Name: "Ethereal Mist Gauntlets", ID: "4885" },
  { Name: "Ethereal Mist Greaves", ID: "4886" },
  { Name: "Indicolite Helm", ID: "4911" },
  { Name: "Indicolite Breastplate", ID: "4912" },
  { Name: "Indicolite Gauntlets", ID: "4915" },
  { Name: "Indicolite Greaves", ID: "4916" },
  { Name: "Legionnaire Scale Breastplate", ID: "5175" },
  { Name: "Legionnaire Scale Pauldron", ID: "5176" },
  { Name: "Legionnaire Scale Bracers", ID: "5178" },
  { Name: "Legionnaire Scale Boots", ID: "5181" },
  { Name: "Shuriken of the Tranquil", ID: "8332" },
  { Name: "Slowstone Amber", ID: "12508" },
  { Name: "Darkmetal Holy Water Sprinkler", ID: "6500" },
  { Name: "Trueheart Shield", ID: "9403" },
  { Name: "Theologian Claymore", ID: "5519" },
  { Name: "Revultant Whip", ID: "5522" },
  { Name: "Darkwar Mask", ID: "2190" },
  { Name: "Ashenbone Abbasi", ID: "5517" },
  { Name: "Ashenbone Axe", ID: "5518" },
  { Name: "Ashenbone Shield", ID: "9402" },
  { Name: "Shiverback-hide Armbands", ID: "1202" },
  { Name: "Shiverback-hide Jerkin", ID: "1201" },
  { Name: "Shiverback-hide Leggings", ID: "1205" },
  { Name: "Shiverback-hide Wristbands", ID: "1203" },
  { Name: "Shiverback-hide Gloves", ID: "1204" },
  { Name: "Valorium Greaves", ID: "4856" },
  { Name: "Umbral Platemail Bracer", ID: "4844" },
  { Name: "Words of Odus", ID: "11868" },
  { Name: "Ashenbone Warhammer", ID: "11534" },
  { Name: "Beckon", ID: "11559" },
  { Name: "Bloodmoon", ID: "11558" },
  { Name: "Briarzephyr", ID: "11556" },
  { Name: "Dawnchaser", ID: "11555" },
  { Name: "Diamond Rod", ID: "11570" },
  { Name: "Encyclopedia Necrotheurgia", ID: "11571" },
  { Name: "Eye of Innoruuk", ID: "20656" },
  { Name: "Gardash", ID: "11564" },
  { Name: "Rakusha Cloak", ID: "11562" },
  { Name: "Rod of Infinite Thought", ID: "11574" },
  { Name: "Rod of Unbound Thought", ID: "11572" },
  { Name: "Shattered Emerald of Corruption", ID: "20484" },
  { Name: "Shield of the Immaculate", ID: "11551" },
  { Name: "Sode of Empowerment", ID: "11561" },
  { Name: "Staff of Elemental Mastery: Earth", ID: "11567" },
  { Name: "Sunderfury", ID: "11550" },
  { Name: "Truesight Hammer", ID: "11565" },
  { Name: "Tunarian Scimitar", ID: "11563" },
  { Name: "Vexthorne", ID: "11557" },
  { Name: "Basoon Haste Gauntlets", ID: "11535" },
  { Name: "Evensong", ID: "11554" },
  { Name: "Hand of the Maestro", ID: "20676" },
  { Name: "Kelin`s Seven Stringed Lute", ID: "11573" },
  { Name: "Mempo of Likato", ID: "11560" },
  { Name: "Shield of the Stalwart Seas", ID: "11552" },
  { Name: "Six Note Blade", ID: "11553" },
  { Name: "Umbral Platemail Helm", ID: "4841" },
  { Name: "Umbral Platemail Breastplate", ID: "4842" },
  { Name: "Umbral Platemail Gauntlets", ID: "4845" },
  { Name: "Umbral Platemail Boots", ID: "4847" },
  { Name: "Umbral Platemail Vambraces", ID: "4843" },
  { Name: "Amygdalan Tendril", ID: "5520" },
  { Name: "Nautilus Shield", ID: "9404" },
  { Name: "Emerald Ring", ID: "10045" },
  { Name: "Words of Requisition", ID: "11865" },
  { Name: "Words of Crippling Force", ID: "11870" },
  { Name: "Girdle of the Diligent", ID: "2500" },
  { Name: "Valorium Helmet", ID: "4851" },
  { Name: "Valorium Chestplate", ID: "4852" },
  { Name: "Valorium Bracers", ID: "4854" },
  { Name: "Valorium Gauntlets", ID: "4855" },
  { Name: "Valorium Boots", ID: "4857" },
  { Name: "Blighted Skullcap", ID: "1232" },
  { Name: "Blighted Robe", ID: "1233" },
  { Name: "Blighted Sleeves", ID: "1234" },
  { Name: "Blighted Armband", ID: "1235" },
  { Name: "Blighted Trousers", ID: "1237" },
  { Name: "Blighted Boots", ID: "1238" },
  { Name: "Eye of Fright", ID: "13151" },
  { Name: "Wand of Lava", ID: "12503" },
  { Name: "Carmine Turban", ID: "1225" },
  { Name: "Carmine Robe", ID: "1226" },
  { Name: "Carmine Sleeves", ID: "1227" },
  { Name: "Carmine Trinket", ID: "1228" },
  { Name: "Carmine Pants", ID: "1230" },
  { Name: "Carmine Boots", ID: "1231" },
  { Name: "Flayed Turmoilskin Belt", ID: "2502" },
  { Name: "Cryosilk Cap", ID: "1211" },
  { Name: "Cryosilk Veil", ID: "1212" },
  { Name: "Cryosilk Choker", ID: "1213" },
  { Name: "Cryosilk Robe", ID: "1214" },
  { Name: "Cryosilk Cloak", ID: "1216" },
  { Name: "Cryosilk Sash", ID: "1217" },
  { Name: "Cryosilk Lined Shoes", ID: "1222" },
  { Name: "Cryosilk Webshield", ID: "9401" },
  { Name: "Eyerazzia", ID: "7508" },
  { Name: "Vermiculated Crown", ID: "3801" },
  { Name: "Vermiculated Tunic", ID: "3802" },
  { Name: "Vermiculated Bracelet", ID: "3804" },
  { Name: "Vermiculated Gloves", ID: "3805" },
  { Name: "Vermiculated Leggings", ID: "3806" },
  { Name: "Dweamorvine Garland", ID: "2501" },
  { Name: "Thorny Vine Helm", ID: "4891" },
  { Name: "Thorny Vine Chestplate", ID: "4892" },
  { Name: "Thorny Vine Bracer", ID: "4894" },
  { Name: "Thorny Vine Gauntlets", ID: "4895" },
  { Name: "Thorny Vine Boots", ID: "4897" },
  { Name: "Wand of Allure", ID: "12507" },
  { Name: "Fluxbladed Axe", ID: "5523" },
  { Name: "Greenmist Helm", ID: "5166" },
  { Name: "Greenmist Breastplate", ID: "5167" },
  { Name: "Greenmist Vambraces", ID: "5168" },
  { Name: "Greenmist Bracer", ID: "5169" },
  { Name: "Greenmist Greaves", ID: "5171" },
  { Name: "Greenmist Boots", ID: "5172" },
  { Name: "Greenmist Mask", ID: "5173" },
  { Name: "Nightmare Hide", ID: "2333" },
  { Name: "Wand of Darkness", ID: "12505" },
  { Name: "Bone Razor", ID: "11661" },
  { Name: "Spined Dragon Claws", ID: "11663" },
  { Name: "Staff of Undead Legions", ID: "11662" },
  { Name: "Withered Totem of Widdershins", ID: "11665" },
  { Name: "Monsoon, Sword of the Swiftwind", ID: "11667" },
  { Name: "Amulet of Necropotence", ID: "11646" },
  { Name: "Barbarian Spiritist`s Hammer", ID: "11647" },
  { Name: "BladeStorm, Katana of Steel Sleet", ID: "11664" },
  { Name: "Blood Fire", ID: "11645" },
  { Name: "Crimson Robe of Alendine", ID: "11641" },
  { Name: "Darkwood Trunk", ID: "17703" },
  { Name: "DawnFire, Morning Star of Light", ID: "11648" },
  { Name: "Lyssa`s Darkwood Piccolo", ID: "11642" },
  { Name: "Puppet Strings", ID: "11643" },
  { Name: "Shield of Rainbow Hues", ID: "11644" },
  { Name: "Soul Leech, Dark Sword of Blood", ID: "11609" },
  { Name: "Staff of the Earthcrafter", ID: "11649" },
  { Name: "Belt of Tranquility", ID: "2917" },
  { Name: "Belt of Virtue", ID: "2919" },
  { Name: "Belt of Contention", ID: "2921" },
  { Name: "Weight of the Gods", ID: "2924" },
  { Name: "Blade of Abrogation", ID: "5430" },
  { Name: "Treant Tear", ID: "12801" },
  { Name: "Symbol of Marr", ID: "12800" },
  { Name: "Stein of Flowing Ichor", ID: "12802" },
  { Name: "Bracelet of Cessation", ID: "12804" },
  { Name: "Bracelet of Exertion", ID: "12805" },
  { Name: "Bracelet of Quiescence", ID: "12806" },
  { Name: "Golden Efreeti Turban", ID: "4341" },
  { Name: "Golden Efreeti Chestplate", ID: "4342" },
  { Name: "Golden Efreeti Vambraces", ID: "4343" },
  { Name: "Golden Efreeti Bracers", ID: "4344" },
  { Name: "Golden Efreeti Gauntlets", ID: "4345" },
  { Name: "Golden Efreeti Greaves", ID: "4346" },
  { Name: "Efreeti War Shield", ID: "20705" },
  { Name: "Efreeti War Axe", ID: "20711" },
  { Name: "Efreeti Scimitar", ID: "20739" },
  { Name: "Efreeti Wind Staff", ID: "20779" },
  { Name: "Efreeti Mace", ID: "20816" },
  { Name: "Efreeti Dirk", ID: "20875" },
  { Name: "Efreeti Standard", ID: "20817" },
  { Name: "Efreeti War Horn", ID: "20830" },
  { Name: "Efreeti War Maul", ID: "20846" },
  { Name: "Efreeti War Spear", ID: "20831" },
  { Name: "Efreeti War Staff", ID: "20753" },
  { Name: "Efreeti War Club", ID: "20845" },
  { Name: "Efreeti Long Sword", ID: "20858" },
  { Name: "Efreeti War Bow", ID: "20861" },
  { Name: "Efreeti Magi Staff", ID: "20870" },
  { Name: "Efreeti Belt", ID: "20976" },
  { Name: "Efreeti Battle Axe", ID: "20983" },
  { Name: "Efreeti Zweihander", ID: "20725" },
  { Name: "Wind Etched Bracers of Ro", ID: "4334" },
  { Name: "Wind Etched Gauntlets of Ro", ID: "4335" },
  { Name: "Wind Etched Boots of Ro", ID: "4337" },
  { Name: "Wind Etched Helm of Ro", ID: "4331" },
  { Name: "Brass Knuckles", ID: "20803" },
  { Name: "Azure Ring", ID: "20971" },
  { Name: "Feathered Cape", ID: "20755" },
  { Name: "Finely Crafted Amulet", ID: "20998" },
  { Name: "Finely Woven Cloth Cord", ID: "20768" },
  { Name: "Grey Damask Cloak", ID: "20742" },
  { Name: "Griffon Talon", ID: "20850" },
  { Name: "Griffons Beak", ID: "20781" },
  { Name: "Inlaid Choker", ID: "20985" },
  { Name: "Leather Cord", ID: "3656" },
  { Name: "Light Woolen Mask", ID: "20821" },
  { Name: "Silken Strands", ID: "20794" },
  { Name: "Silver Hoop", ID: "20807" },
  { Name: "Worn Leather Mask", ID: "20729" },
  { Name: "Black Silk Cape", ID: "20783" },
  { Name: "Ceramic Mask", ID: "20757" },
  { Name: "Cracked Leather Eyepatch", ID: "20796" },
  { Name: "Fine Velvet Cloak", ID: "20853" },
  { Name: "Jester's Mask", ID: "20987" },
  { Name: "Light Cloth Mantle", ID: "20770" },
  { Name: "Light Woolen Mantle", ID: "20823" },
  { Name: "Mantle of Woven Grass", ID: "20731" },
  { Name: "Shimmering Amber", ID: "20837" },
  { Name: "Silvery Ring", ID: "20700" },
  { Name: "Small Shield", ID: "20809" },
  { Name: "Stone Amulet", ID: "20973" },
  { Name: "Woven Skull Cap", ID: "20744" },
  { Name: "Ceremonial Belt", ID: "20838" },
  { Name: "Crude Wooden Flute", ID: "20825" },
  { Name: "Dove Slippers", ID: "20798" },
  { Name: "Fine Cloth Raiment", ID: "20785" },
  { Name: "Finely Woven Cloth Belt", ID: "20702" },
  { Name: "Golden Coffer", ID: "20759" },
  { Name: "High Quality Raiment", ID: "20746" },
  { Name: "Light Damask Mantle", ID: "20840" },
  { Name: "Shiny Pauldrons", ID: "20811" },
  { Name: "Silken Mask", ID: "20772" },
  { Name: "Spiroc Air Totem", ID: "20975" },
  { Name: "Spiroc Battle Staff", ID: "20733" },
  { Name: "Spiroc Earth totem", ID: "20855" },
  { Name: "Spiroc Elders Totem", ID: "20867" },
  { Name: "Spiroc Sky Totem", ID: "20989" },
  { Name: "Spiroc Wingblade", ID: "20679" },
  { Name: "Adamantium Earring", ID: "20774" },
  { Name: "Bixie Stinger", ID: "14029" },
  { Name: "Divine Honeycomb", ID: "20735" },
  { Name: "Box of Winds", ID: "20748" },
  { Name: "Corrosive Venom", ID: "20842" },
  { Name: "Dull Dragon Scale", ID: "20926" },
  { Name: "A fine wool cloak", ID: "20991" },
  { Name: "Rusted Pauldrons", ID: "20704" },
  { Name: "Silken Wrap", ID: "20800" },
  { Name: "White Gold Earring", ID: "20857" },
  { Name: "Wind Tablet", ID: "20978" },
  { Name: "Silvered Spiroc Necklace", ID: "20813" },
  { Name: "Amethyst Amulet", ID: "20750" },
  { Name: "Circlet of Brambles", ID: "20860" },
  { Name: "Djinni Aura", ID: "20815" },
  { Name: "Djinni Stave", ID: "20765" },
  { Name: "Djinni War Blade", ID: "20980" },
  { Name: "Ethereal Ruby", ID: "20737" },
  { Name: "Glowing Diamond", ID: "20829" },
  { Name: "Glowing Necklace", ID: "20776" },
  { Name: "Golden Efreeti Ring", ID: "20763" },
  { Name: "Ring of Veeshan", ID: "20789" },
  { Name: "Sphinx Claw", ID: "20724" },
  { Name: "Sphinxian Circlet", ID: "20993" },
  { Name: "Sphinxian Ring", ID: "20709" },
  { Name: "Spiritualist`s Ring", ID: "20844" },
  { Name: "Efreeti Great Staff", ID: "20792" },
  { Name: "Ethereal Emerald", ID: "20982" },
  { Name: "Fae Pauldrons", ID: "20710" },
  { Name: "Mithril Bands", ID: "20819" },
  { Name: "Symbol of Veeshan", ID: "20847" },
  { Name: "Tear of Quellious", ID: "20805" },
  { Name: "Crown of Elemental Mastery", ID: "20764" },
  { Name: "Belt of Iniquity", ID: "2918" },
  { Name: "Belt of Concordance", ID: "2920" },
  { Name: "Belt of Transience", ID: "2922" },
  { Name: "Blood Sky Amethyst", ID: "20762" },
  { Name: "Bracelet of Distortion", ID: "12803" },
  { Name: "Cracked Leather Belt", ID: "20992" },
  { Name: "Adamantium Bands", ID: "20828" },
  { Name: "Ivory Pendant", ID: "20758" },
  { Name: "Dragon-hide Mantle", ID: "20854" },
  { Name: "Belt of the Pine", ID: "2916" },
  { Name: "Dried Leather", ID: "20701" },
  { Name: "Spell: Spirit of the Howler", ID: "19275" },
  { Name: "Spell: Talisman of the Brute", ID: "19281" },
  { Name: "Nature Walker's Sky Emerald", ID: "20730" },
  { Name: "Lustrous Russet Bracer", ID: "4834" },
  { Name: "Lustrous Russet Boots", ID: "4837" },
  { Name: "Lustrous Russet Breastplate", ID: "4832" },
  { Name: "Lustrous Russet Gauntlets", ID: "4835" },
  { Name: "Lustrous Russet Helm", ID: "4831" },
  { Name: "Lustrous Russet Greaves", ID: "4836" },
  { Name: "White Satin Gloves", ID: "2923" },
];
